name: Update README and Generate Snake Animation

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta a medianoche todos los días para actualizar el README
    - cron: '* */12 * * *'  # Ejecuta cada 12 horas para la animación de la serpiente

  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate-snake:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-readme:
    runs-on: ubuntu-latest
    needs: generate-snake
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update README
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./path-to-your-updated-readme

